---
title       : "Using machine learning to identify early predictors of adolescent emotion regulation development"
authors     : "masked"
journal     : "Journal of Research on Adolescence"
editor      : "Raval"
manuscript  : "2022-182"
class       : "draft"
mask: no
bibliography      : ["manuscript/r-references.bib", "manuscript/references.bib", "manuscript/Veni.bib"]
output      : papaja::revision_letter_pdf
---

```{r, message=FALSE, warning=FALSE}
library(revise)
test_env <- new.env()
read_manuscript("c:/git_repositories/veni_forest/manuscript/manuscript.Rmd", envir = test_env)
read_manuscript("action_letter.Rmd", envir = test_env)
mask = TRUE
```

Dear Dr. `r rmarkdown::metadata$editor`,

Thank you for considering our manuscript for publication in _`r rmarkdown::metadata$journal`_.
We appreciate the thorough and critical comments you solicited,
which helped strengthen the argumentation, clarify the structure, and add nuance.
We have attempted to address all comments as thoroughly as possible.
All changes are explained below.
We hope that you will find the quality of the work to be sufficiently improved.

Yours sincerely,

the authors

# Editor {-}

\RC{In the introduction section, please provide a comprehensive review of the literature. As reviewer 3 points out, there is existing literature investigating risk factors associated with emotion dysregulation. This research needs to be cited.}

We completely agree with Reviewer 3 that there is already a wealth of prior research in this area.

`r get_revision("priorlit", quote = F)`

\RC{Also, please specify the demographics of the samples of cited studies. A bulk of the literature in our field, including related to emotion dysregulation, is based on samples from Western countries (e.g., Australia, those in North America, and those in Europe). If the studies you are citing are from these world regions, please specify that.}

First, as mentioned above, the vast majority of cited studies are reviews (narrative reviews, meta-analyses, and book chapters) or theoretical publications.
Although one would hope that such publications cover all available literature without selecting for country of origin,
some bias is likely present.
Of the few primary empirical studies we cited, all originated in the "Global North" (if one also considers Israel and Greece to be part of the Global North).
To address this comment, we have extracted information about the country of origin of the samples of all primary data sources cited.
This information is summarized in a new Supplemental Table,
which also indicates what references are *not* primary data sources but instead theoretical, review, or methodological articles.

To address this comment, we now state the following in the Limitations section:

`r get_revision( "globalnorth")`

<!-- Second, this is not a hypothesis-testing study. It doesn't matter whether findings from previous samples generalize to the present one, because we do not deduce hypotheses from previous work. All that matters is whether our findings can be generalized to other samples. -->

\RC{Also, you describe two major theories of development including the bioecological theory (Bronfenbrenner \& Morris, 2007). Note that there is a revision to Bronfenbrenner’s model that places culture as existing in different settings and not only as a distal influence as a macrosystem (see Velez-Agosto et al., 2017). According to this revision, cultural processes are not distal influences, instead cultural and individual processes interact in a transactional fashion and this revised model is actually much more aligned with the Transactional model (Sameroff, 2010) that you reference.}

To address this comment, we have incorporated the following into the Introduction:

`r get_revision( "velez1")`

And the following in the Discussion:

`r get_revision( "velezagosto")`

\RC{In the method section, it would be helpful to include when (months and year) and where the data are collected (geographic location/country). Given cultural differences in emotion regulation, the context of the sample is really critical to include.}

We respectfully believe that this may have been an oversight,
as the requested information was already provided. As per the submission guidelines, some specific details had been masked for review, which may have caused the confusion. To address this comment, we have unmasked these details in the revision:

Timing of data collection (we do not have information about specific months):

`r get_revision( "waves")`

Geographic location:

`r get_revision( "dutch")`

\RC{Also, as reviewer 1 suggests, please explain the methodology used to extract predictors in more detail.}

`r get_revision("extractpreds", quote = F)`

\RC{In the results and discussion, as reviewer 2 and 3 highlight, please be careful about interpreting your findings. For example, to refer to parenting as unimportant based on your findings seems inaccurate given that balanced relatedness was the 3rd ranked predictor, so rather than say that parenting was unimportant or underrepresented, state that some dimensions of parenting were important, and name those dimensions.}

<span id = "parents">We now realize that our imprecise use of language caused confusion about the relative importance of what we previously called "parenting" - by which we meant specific parenting practices.

In the revision, we have attempted to avoid confusion by distinguishing "parenting practices" from other "parent-related constructs".
Parenting practices are defined as specific parental actions related to child-rearing,
for example, support and dimensions of control [@petersonFamilySocialCompetence1990].
The highest-ranking parenting practice is parental control of friendships (16).

By contrast, parent-related constructs refer to any variable pertaining to a parent but that is not a parenting practice.
The highest ranking parent-related construct is balanced relatedness (3),
which measures whether the adolescent perceives his or her parents to be tolerant of the adolescent's differing beliefs.
Balanced relatedness is an aspect of the emotional family climate [@morrisRoleFamilyContext2007],
not a parenting practice, because it does not relate to specific parental actions.
The parenting practices associated with instilling a sense of balanced relatedness are maternal (54) and paternal (55) support, which rank very low.

The observation that parenting practices are relatively less important than individual predictors (and certainly much less important than we would have thought a-priori) is thus strongly supported by the data;
the first such behaviors are (16) and (25).
This conclusion is not contradicted by the finding that some parent-related constructs score highly.

To address this comment, we have:

- Clarified the distinction between parenting practices and other parent-related constructs in the revision
- Used consistent terminology throughout 
- Provided a definition of parenting practices

We have rewritten the following paragraphs:

`r get_revision( "parenting")`

And:

`r get_revision( "parentrelated")`
</span>

\RC{In the discussion, I encourage you to think about predictors from the revised bioecological theory perspective (Velez-Agosto et al., 2017) that does not conceptualize individual level, micro- and macro as influences that move along the proximal to distal continuum and conceptualizes them in a transactional framework. Factors such as religiosity and social class are reflected in relationships with parents and peers and thus to state that they are less important because they are ranked lower may not capture the complexity of their relevance.}

We thank the Editor for this excellent suggestion; we have addressed this comment by adding the following to the Introduction:

`r get_revision( "velez1")`

And the following to the Discussion:

`r get_revision( "velezagosto")`


\RC{Also, as you mention in the limitations, it is possible that SES was ranked low because of the restricted range of SES that was represented in your sample.}

If we understand correctly, this is a statement and requires no further action.

\RC{In the discussion, it is stated, “Predictors at the individual level were most important, followed by those at the microsystem level, such as aspects of the relationship with parents, followed by the mesosystem, including aspects of the peer network (e.g., bullying/victimization and delinquency), school performance, and socio-economic status, and the macrosystem indicator religiosity was among the least important predictors.”  This statement does not seem to fit the findings. If you look at the top 10 predictors listed in table 2, they include individual characteristics (big 5) and relational aspects (balanced relatedness, conflict). Please revise. Also, there are frequent references to individual level predictors being the most important and again looking at the top 10 predictors in table 2, there are both individual characteristics and relational dimensions so please revise the language.}

Reviewer 2 suggested that we include a Figure to illustrate the distribution of variable importances by level of the bioecological model and by theme, to illustrate the two ways we interpret the pattern of findings (see Figure 3).
We believe that this figure substantially clarifies our interpretation of the results.

Furthermore, to address the specific comment that "Predictors at the individual level were most important [etc]", we now refer to Figure 3 so readers can see the pattern we are describing.
At the same time, we now explicitly acknowledge that there is substantial overlap in importance of predictors at the different levels: 

`r get_revision( "overlap")`

# Reviewer: 1

\RC{It was a delight to read this manuscript that applied multiple novel machine learning methods to identify the most important early predictors of adolescent emotion regulation development. I found this manuscript to be one of the most innovative, potentially revolutionary manuscripts I have read in a long time. I absolutely think it should be published eventually. I have several suggestions and clarifying questions, provided by section below, that, if addressed, would further strengthen the manuscript. Specifically, I think addressing many of my suggestions would allow the manuscript to be even more translatable and understandable by traditional hypothesis-testing longitudinal researchers like me.

However, again, I want to emphasize that overall I found this manuscript to be absolutely enthralling, and I look forward to seeing it published. Bravo to the authors!}

We thank the Reviewer sincerely for these kind words, and for their constructive feedback. We have attempted to address all comments to the best of our ability.

\RC{It looks like a reference needs to be added to this line: “linear models limit the total number of predictors that can be included due to concerns of power, overfitting, and multicolinearity [REF].”}

We thank the Reviewer for pointing this out. We have inserted the correct reference.

\RC{When the authors state that “The RMSEA and SRMR of the invariant model indicated acceptable fit..”; I am assuming they are talking about the metric invariant model correct? It might be important to add the word “metric” just to specify that.}

We thank the Reviewer for pointing this out. We have made the requested change.

\RC{This is not something that needs to be answered in the text, but what do the authors make of the relatively poor CFI model fit, compared to RMSEA and SRMR. Any idea what accounts for that? I think the authors make a convincing enough argument as is for retaining the chosen model despite the low CFI test statistic, but I was just wondering how they interpreted that divergence in omnibus fit statistics.}

The performance of these fit statistics has been validated mostly in the context of cross-sectional data, and their performance is less well understood for longitudinal data.
This may affect the CFI more than, e.g., RMSEA, because CFI compares the fit of the theoretical model to a null model that may be less appropriate for repeated measures.
We now address this point in the revision:

`r get_revision( "cfi")`

\RC{The Link to Supplementary Table S1 was broken; I couldn’t access it.}

We apologize; the Repository hosting these Supplementary Tables was still set to private at time of submission. This was intended to guarantee anonymous review. For this revision, it has been made public. The links now work.

\RC{I have a couple of items about the approach to missing data used (that, if there is not room in the text, can certainly be provided in a supplement). It mentions that this method is valid when missingness is either random or contingent on observed data. Can you present some evidence that missingness was MAR or MCAR here?}

We respectfully believe that this comment might be based on a misunderstanding. There are three types of missingness: MCAR, where missingness depends on observed data and those observed data can be used to impute; MAR, where missingness is truly random and it doesn't matter if observed data is used to impute; and MNAR, where missingness depends on unobserved data and can therefore neither be detected nor correctly imputed.

No test exists to exclude MNAR. For example, Little's MCAR test and non-parametric alternatives like Jamshidian & Jalal's non-parametric test can provide *evidence confirming MAR*, but the presence or absence of MAR does not exclude MNAR.

The present methods are valid for both MCAR and MAR - so there is no need to provide evidence for either of those.

Also note that no MCAR test exists for cases where the number of variables is higher than the number of participants (N < p): In this case, the raw data, prior to imputation and scale construction, is 495 (participants) x 750 (variables) big, so N < p.

\RC{Additionally, and relatedly, were there any systematic differences between those with missing and complete data? That would also be good for the reader to know.}

<span id = "missingness">To address this comment, and a comment by another Reviewer, we tested for differences on demographic characteristics and the dependent variable between participants with missing and complete data. We now mention this in the revised manuscript:

`r get_revision( "missing")`
</span>

\RC{I think that the methodology used to extract predictors here is ground-breaking and pretty revolutionary. However, that also means that the procedure might need to be explained in a little more depth for “old methodologists” like me. I actually think because this procedure is so innovative in the field of psychology, I would humbly be in favor of expanding the page limits of the manuscript to provide clarification on some of these questions in further detail, only because as a “tried and true” frequentist longitudinal modeler who is beginning to dabble in machine learning, I (and I suspect many like me) would love to learn even more about this procedure. Here are a few questions I had about it.
o The authors note that for multi-item scales, they used principal components analysis for dimension reduction and took the first component for further analysis. Could, perhaps, the authors provide a specific example to make this process even more “concrete” in the minds of readers. Perhaps the authors could provide an example of how this was done on a single scale, what items were included as part of the first component that represents large amounts of shared variance, etc.}

We appreciate the Reviewer's kind words.
<span id = "extractpreds">
The method used to extract predictors is less groundbreaking than the Reviewer gives us credit for. PCA is the oldest dimension reduction technique (invented in 1901), and the main reason we use it here is because it makes fewer assumptions about the measurement model than, e.g., CFA.

We appreciate the Reviewer's excellent suggestion of providing a specific example to help readers understand this approach. To address this comment, we have thus made the following changes:

1. We added the requested illustrative example, using neuroticism. We could use any scale, but as Neuroticism later turns out to be the most important predictor, it seems a suitable candidate.
2. We have clarified our description of the dimension reduction procedure
3. We have added further statistics that, hopefully, give the reader a better sense of whether the use of these principal components is defensible. Specifically, we no longer just provide the explained variance by each first component - but we also standardize this explained variance by the number of items in the scale to see how much more variance the first component explains than expected by chance. We see that, across all scales, the first component explains between 1.6 - 17.46 times more variance than expected by chance.
</span>

\RC{I see that in the SEM-forest analysis, homoscedastic residuals over time were assumed. I am guessing the reason for doing so is because estimating heteroscedastic residuals over time just makes the model hopelessly complex and unestimable. So my question here is two-fold: First, is that true? Second, can the homoscedasticity versus heteroscedasticity of residuals be tested in similar ways as it can in traditional growth curve modeling here? I don’t at all mind if homoscedastic residuals need to be assumed to ensure the model runs (I think that is the implication from the limitation mentioned in the discussion).}

The Reviewer is correct; homoscedastic residuals were assumed because otherwise the model would be "hopelessly complex". We would have more parameters for the residuals than for the rest of the model, and the SEM-forest analysis would thus be primarily driven to explain differences in residuals, instead of in growth curves.
Unfortunately there is no way to test this assumption. The SEM-forest method estimates tens to hundreds of thousands of SEM models in across all nodes in all trees. It is not possible to test model assumptions in each of those nodes.

We have attempted to address this comment as follows: By explaining our decision to assume homoscedasticity:

`r get_revision( "homogeneity")`

And by addressing it further in the Limitations section:

`r get_revision( "homogeneity2")`

\RC{Could you speak a little more (maybe just a sentence or so) on the importance of step 2 substep iii. In the SEM forest algorithm? It was hard for me to follow why identifying the value of preditor k that maximizes the likelihood ratio of a post-split two-group model indicates best model fit. I suspect just another sentence or so of clarification is needed.}

We have rewritten this step in an attempt to address this comment. It now reads:

`r get_revision( "stepiii")`

\RC{Could you speak more to the importance of why steps 3 and 4 need to be repeated until all post-split groups reach a minimum size? What would that minimum size be and why is it important?}

To address this comment, we have rewritten this step as follows:

`r get_revision( "fullygrown")`

Additionally, we have rewritten the introduction to the SEM-forests algorithm to provide more context, thereby hopefully making it easier for readers to grasp:

`r get_revision( "semforests")`

\RC{How are predictions aggregated from all SEM-trees? If you could offer even just a sentence or two on that process in a way a “traditional” “applied” longitudinal researcher (like me) would understand, I think such readers would be very grateful.}

We have added the following explanation:

`r get_revision( "predictions")`

\RC{Could you provide a quick applied example to accompany this statement “This approach intrinsically accommodates non-linear effects as subsequent splits on the same predictor, and complex interactions as subsequent splits on interacting variables. This offers greater flexibility than linear parametric models.”. Again, I think providing an example would allow non-machine learning researchers to follow what you are doing here even more clearly.}

We have added the following example:

`r get_revision( "nonlinearexample")`

\RC{I think the results clearly presented a complex set of findings. I really appreciated the grouping by theme.
• I have seen many ML applications split data sets into “train” and “test” sub-samples, to validate the findings in the “train” data set in the “test” data set. As far as I can tell, that was not done here. Did the authors consider this approach? I feel like having “test” and “train” sub-samples wherein results are replicated would provide further robustness and validity to study findings. I also understand if that procedure is not possible with the SEM forests approach.}

Thank you for bringing up this point. This is indeed common practice in "standard" machine learning, but unfortunately not possible for SEM-forests because there is (currently?) no error metric that could be used to describe fit in a "test" sample. For a standard regression tree, one can calculate mean squared error, or even $R^2$ in the training data. For SEM-trees, it's not clear what one would calculate.

We had mentioned this in the Limitations section, but evidently that statement was not sufficiently clear. To address this comment, we have rewritten that section as follows:

`r get_revision( "limitations")`

\RC{I know ensuring the article remains inside page limits is always a battle, but I had a suggestion for one additional, hopefully simplistic analysis that might even further bridge the “gap” between these machine learning analyses and “traditional, frequentist” analyses. Perhaps the authors could take only the most important predictors, say the top 10 (or really whatever number they want), and run regression analyses that predict trajectory intercepts and slopes? Basically, I know that people like me really like explanations like “oh yeah, these top 10 machine learning predictors predict XX\% of variance in emotion regulation scores over time”, and so I was trying to think of a way to generate those sorts of tangible, “traditional” effect sizes. Could the authors potentially provide such effect size estimates? I also understand if there simply isn’t time or space for this, but figured it was worth asking.}

Thank you for this suggestion; we agree that many people would be interested in such an overview. One major caution is that such post-hoc analyses should not be over-interpreted; they are in no way a substitute for the (much more flexible) machine learning models. Still, we see that having an overview of univariate linear effects might be useful, for example, to determine expected effect sizes if people want to take guidance from our list of important predictors to help plan follow-up studies.

To address this comment, we have therefore added the following paragraph and an additional Supplemental Table:

`r get_revision( "posthoc")`

\RC{I appreciated the brave and nuanced discussion of how these analyses conform to, and also challenge, traditionally held norms in the field of emotion regulation. I especially appreciated the identification that parenting, substance use, and bullying might not be the risk factors we think they are.}

We thank the Reviewer for these kind words. We share the Reviewer's enthusiasm for the potential change in perspective implied by these findings - although we understand the importance of tempering that enthusiasm as this is just a single preliminary study, with considerable limitations.

\RC{The ERRATA tool seems amazing; I couldn’t find it online. Could a link be provided directly in the text?}

To address this comment, we have added the following information:

`r get_revision( "errata")`

\RC{I love the notion of “good enough” parenting environment and preconditions, and its’ application here; I thought the link between non-linear effects and “good enough” parenting environments was such an incredible example of translating a statistical insight into “on the ground” wisdom that can be applied by clinicians.}

Thank you for these kind words!

\RC{The only part of the results that were left relatively untouched by the Discussion was the relatively large importance of Big 5 personality traits as predictors of adolescent emotion regulation. Could the authors comment on what they thought about those findings? I am especially interested to hear the authors thoughts about those results, because I feel like investigation of personality traits is so often “siloed” away from investigation of parenting, substance use, and other phenomena when it comes to adolescent emotion regulation. So I think it would be especially important to also highlight those findings in the Discussion.}

We thank the Reviewer for this hepful suggestion, and have written the following to address it:

`r get_revision( "includepersonality")`

\RC{I think there are some broken links to supplemental materials in the manuscript.}

This is correct; at the time of submission, the repository on GitHub was still set to private to safeguard blind review. For the revision, this has been resolved.

\RC{I think the authors should just re-read the manuscript again before final publication; there were missing words and sentences throughout in some places.}

We have done as suggested and corrected any errors found.

\RC{Pages 43 to 65 of the manuscript materials appeared cut-off and unreadable in many areas.}

We apologize for the inconvenience. The manuscript only has 42 pages; pages 43-65 are copies of the online supplemental materials (the same Tables that were supposed to be accessed via the broken links, which are now fixed). For the sake of blind review, we also submitted copies of these tables through the submission portal, but it evidently cannot correctly present these materials. The tables will not be part of the paper in this form.

# Reviewer: 2

\RC{I reviewed this manuscript from the perspective of a clinical psychologist with expertise in quantitative methods and adult psychopathology. I have years of experience with and expertise in applied predictive modeling and supervised machine learning in general but am not that familiar with the SEM forest algorithm, which seems to blend supervised and unsupervised learning. Thus, I defer to other reviewers to evaluate the substantive aspects of the manuscript related to adolescent emotion regulation development and the highly technical aspects of the manuscript specific to the SEM forest algorithm.

Overall, I found the manuscript to be ambitious and interesting. The size and longitudinal nature of the dataset is impressive, even if it the number of participants is a bit lower than one might ideally want to support complex machine learning. I also valued the manuscript’s integration of theory and methods, transparency of the methods, the addition of variable importance functions to the semTrees package, and the creation of the Shiny app as a demo/first step towards implementation. My concerns are mainly around the lack of external cross-validation (I realize that the out-of-bag approach is like an internal cross-validation) and hyperparameter tuning (which may be related to differences between the supervised approach I am used to and the hybrid approach of SEM forest) as well as some apparent discrepancies between the results as I understand them and the conclusions in the manuscript.}

We thank the Reviewer for their kind words and thoughtful comments, which have been instrumental in improving the manuscript.
Please see our detailed responses to the specific comments below.

\RC{1. I think that the number of predictors used should be tuned during cross-validation rather than set to 9 or, at least, multiple values should be compared. Similarly, I think that the complexity parameter should be tuned or compared. Please comment on why this wasn’t done.}

Model tuning and cross-validation are indeed industry standard procedures in machine learning.
However, these methods do not (yet?) exist for SEM-forests.
This is because there is no single error metric for SEM-forests that can be optimized.
For standard random forests, this error metric is the root mean squared error (difference between predicted and observed values for all cases).
The "outcome" of each regression tree in the SEM-forest is an entire SEM-model, for which there is no clear-cut case-specific error metric.
It is important to note, however, that unlike other machine learning techniques, random forests typically achieve competitive performance even with default settings [@probstHyperparametersTuningStrategies2019].
Thus, even when a random forest isn't tuned - or cannot be tuned, as is the case here - it should perform well.
Although we did attempt to explain these points in the previous version of the manuscript,
we have attempted to address this comment by further emphasizing this in the Revision:

`r get_revision( "limitations")`

\RC{2. On page 15, there seem to be semantic themes or groupings of predictors. In addition to textual interpretation, I think it would be helpful to create a visualization (even if it were supplemental) that grouped the variable importance scores per theme. Perhaps each theme could be represented by a boxplot or jittered points. This would help communicate the relative importance of each theme (as the text is currently doing informally). A similar approach could be employed for predictors assigned to different levels of the bioecological model.}

We thank the Reviewer for this excellent suggestion, and have now included a new Figure (Figure 3) that clusters variable importances by (inductive) theme as discussed in the results section, as well as by level of the bioecological model.
We now refer to this Figure when discussing the relative importance of each theme / level.

\RC{3. The manuscript’s conclusion that parenting behaviors (especially positive ones) are low in importance (e.g., page 18) is hard for me to reconcile with the third-most important predictor being a positive parenting behavior. Overall, there seems to be an interpretive bias against the parenting behaviors being important. Or perhaps I am misunderstanding something?}

We thank the Reviewer for pointing out the apparent inconsistency between the conclusion and results.

First, we really want to stress that we are not biased against parenting; much of our prior work has focused on the effect of specific parenting practices on child development.
This notwithstanding, we were legitimately surprised that these same specific parenting behaviors ranked surprisingly low in machine learning analysis - although we understand and acknowledge that this is just a single preliminary study, with considerable limitations.

Second, with regard to the Reviewer's statement that "the third-most important predictor being a positive
parenting behavior". Balanced relatedness is not a parenting practice (i.e., a specific action parents engage in as part of child rearing). Rather, it is an aspect of the (adolescent-perceived) emotional family climate. `r get_revision("parents", quote = F)`

We also believe that Figure 3 helps clarify these results.

\RC{4. On page 12, it seems to me that the interpretation of SEM-forests answering, “why do some adolescents have similar growth trajectories” has some causal connotations that may or may not be intended. Please speak to this directly in the manuscript. Can SEM-forests enable causal inferences, or would it be more accurate to rephrase this sentence to remove the connotation?}

We agree with the Reviewer that is is prudent to caution against undue causal interpretation of the results - which we have done in the Limitations section:

`r get_revision( "causality")`

We do believe that the quoted statement is correct and does not require further modification, however, as it does not relate to causal interpretation of the results, but to the affordances of the method: latent class analysis *cannot* answer the question "Why?" some adolescents follow similar causal trajectories,
whereas SEM-forests *can* answer this question, because cases are clustered based on predictor variables.
As is the case for all statistical analyses, this comes with the caveat that causal interpretation is contingent on study design or theoretical justification.

\RC{5. My understanding is that the importance of specific interactions can be interrogated using an generalization of partial dependence profiles (Apley \& Zhu, 2020). I’m not saying that this necessarily has to be added to the current paper, but it might be worth citing this approach in the “next steps” part of the manuscript and considering it in future work.}

We appreciate the suggestion and had considered a similar approach - but it is not practically feasible for the following reasons:

1. Computing univariate partial dependence profiles is extremely computationally expensive; bivariate partial dependence is prohibitively so.
2. There is no a-priori way to determine which bivariate interactions might be important in SEM-forests analysis (because there is no applicable analogy for Friedman's H statistic).
3. Consequently, one would have to examine all bivariate interactions by hand. This comes down to interpreting 84\*84\*3 = 21168 plots. This is not possible.

With this in mind, we think it would be preferable *not* to muddy the waters by citing literature on interaction effects for random forests; not until suitable methods have been developed for SEM-forests as well.

\RC{6. That said, my understanding is that partial dependence profiles can be somewhat problematic when applied to correlated predictors (as these predictors surely are) and that a better approach in such cases would be accumulated local profiles (Apley, 2018).}

Again, we thank the Reviewer for the suggestion;
in principle this is correct, but in practice, no method (currently?) exists to obtain accumulated local effects for SEM-forests.
The Reviewer is citing cutting-edge developments in the area of classic random forests, which are not yet widely adopted or implemented for different algorithms;
it will take a while before these developments spill over into the SEM-forests literature.

\RC{1. On page 10, please clarify whether the CFAs were single factor models.}

We respectfully believe that this may be an oversight on the Reviewer's part, because the manuscript says:

`r get_revision( "singlefactor")`

We do not believe further action is required on this point - but if we missed something, please let us know.

\RC{2. On page 10, please provide more explanation of the discrepancy between absolute and comparative fit of the metric invariant model.}

The performance of these fit statistics has been validated mostly in the context of cross-sectional data, and their performance is less well understood for longitudinal data.
This may affect the CFI more than, e.g., RMSEA, because CFI compares the fit of the theoretical model to a null model that may be less appropriate for repeated measures.
We now address this point in the revision:

`r get_revision( "cfi")`

\RC{3. In figure 1, clarify whether the y-axis is reversed. I ask because it seems strange to me that someone with lower difficulties with emotion regulation would be “high risk” and Figure 1 seems to show the opposite pattern as Figure 7.}

We apologize for the oversight; the y-axis was indeed reversed in this Figure. We have corrected this mistake.

\RC{4. On page 12, please speak to the reasonableness of the assumption of homoscedastic residuals over time.}

We assumed homoscedastic residuals because otherwise the model would be too complex to estimate. We would have more parameters for the residuals than for the rest of the model, and the SEM-forest analysis would thus be primarily driven to explain differences in residuals, instead of in growth curves.

A SEM-forest method estimates tens, or hundreds of thousands of SEM models in its different nodes. It is not possible to test model assumptions in each of those nodes.
This applies not only to the assumption of homogeneity of residuals, but to all other assumptions, for example, about normality of residuals, or the shape of the growth trajectories. 

We have attempted to address this comment by explaining our decision to assume homoscedasticity:

`r get_revision( "homogeneity")`

And also, by addressing it in the Limitations section:

`r get_revision( "homogeneity2")`

\RC{5. On page 14, the reference to Figure 1 should be to Figure 2.}

We have corrected this mistake.

\RC{6. I think Figures 5 and 6 could be moved to supplemental if space is tight.}

We thank the Reviewer for the suggestion,
and defer to the Editor on this point.

\RC{7. On page 18, is it true that “out [of] all parent-related constructs, constructive conflict resolution with fathers ranked highest and, and out of all parenting behaviors, paternal power ranked highest”? This seems to only be true if you look at only the mother/father-specific parenting measures and omit the general ones like balanced relatedness and conflict interparental.}

We have clarified this by writing:

`r get_revision( "motherfather")`

\RC{8. The supplemental table 1 didn’t render well in the PDF.}

We apologize for the inconvenience. These Supplemental Tables will not be part of the printed manuscript; we were required to attach hard copies of the online supplemental tables in the submission portal, and these were evidently not formatted correctly. They are just spreadsheets that can be opened in a web-browser or excel. The links to these Supplemental Tables in the manuscript now work.

# Reviewer: 3

\RC{The abstract could be strengthened by providing theoretical rationale for the study. The abstract also seems to exceed the journal’s word limit, as several sentences are cut off on the version included in the pdf cover page. In describing the results for parenting behaviors, it seems that autonomy support and invasive parenting were important if I am reading the statement correctly, so please remove these from the “less important” statement in order not to undermine the importance of parenting.}

We appreciate these suggestions and the caution about abstract length; we have cut the abstract by half and incorporated the Reviewer's suggestions. The Abstract now reads:

`r get_revision( "abstract")`

\RC{Please provide citations for the statement in the first paragraph on page 4, “These difficulties in emotion regulation can cause…” and provide examples of why these incur societal cost.}

The statement is a continuation of the preceding sentence,
which is supported by two references. 
To address this comment, we now also added one of these references to the second sentence, and emphasize the connection between the sentences by re-iterating that the societal cost is incurred via emotion regulation-related mental health problems:

`r get_revision("cost", man)`

\RC{I would suggest removing reference to “destinies” on page 4 and elsewhere, as this word connotes fixedness in developmental outcomes, which does not reflect contemporary developmental views.}

We agree with the Reviewer that the word "destinies" has unintended connotations of fixedness in developmental outcomes.
We certainly want to avoid this implication, and have rephrased all occurrences of "diverging destinies" with "diverging trajectories", which is a statistically accurate description of our outcome of interest.

\RC{The introduction would benefit from proofreading for parallel structure (last sentence in first paragraph on page 4), fragments (e.g., “For example, because they are not…”), and other typos (e.g., “an important challenges” on page 8). These are just several examples. The entire manuscript requires proofreading. The Discussion has sentences that are fragments or are missing words.}

We have attempted to correct all such errors.

\RC{At the bottom of page 5, it is noted that the next step in this area of research is to identify risk factors associated with emotion dysregulation. There is a wealth of research already identifying various risk factors. It should be acknowledged that this work exists (and what these identified factors are – some of which are reviewed beginning at the bottom of page 7) before noting the problems with existing research and theory. I would suggest expanding beyond the small number of labs currently heavily relied upon for background on emotion regulation. It seems that the actual next step for this literature is what is defined at the top of the first full paragraph on page 8 – “What is still missing is an understanding of the relative utility…” In short, the introduction could better acknowledge what we already know and more precisely describe the contribution of this study. I expect this would require a fairly extensive revision to move forward.}

First, we agree that this choice of words was unfortunate.
We did not mean to imply that such research has not yet been conducted.
The purpose of this sentence was to emphasize that it is *important* to examine risk factors and lead into the following 3-page section which addresses what is already known.
To clarify this, we have rewritten this sentence and the next as follows:

> `r get_revision("nextstep", man, quote = FALSE)` [...] `r get_revision("fragmented", man, quote = FALSE)`

A second issue is whether our writing sufficiently acknowledges prior research on predictors of emotion regulation.
We could not agree more with the Reviewer that there is a wealth of prior research in this area.
<span id = "priorlit">In fact, a recent (2021) systematic review identified 6305 studies on factors associated with adolescent emotion regulation.
Given this exceedingly large volume of prior literature,
we found it necessary to rely primarily on review articles and theoretical articles to do justice to prior work.
We currently cite 17 review articles and 12 theoretical pieces,
none of which were restricted to any one lab.
We thus respectfully disagree that we only address studies from a "small number of labs".

We cannot strive to recreate a comprehensive review here - 
and this also seems redundant, given that many of the cited review articles are very recent (i.e., from 2019-2021),
and overly ambitious, given the page limits and attention that must be devoted to explaining the novel methods,
and spurious, given that this is an exploratory study and thus has no hypotheses that must be supported with prior literature.

This notwithstanding, we are willing to include **specific** omitted literature, but it is not clear from the Reviewer's comment which specific references should be included.

To address this comment, we now emphasize more strongly that there is an abundance of prior literature on predictors of adolescent emotion regulation, e.g.:

`r get_revision( "abundantlit")`
</span>

\RC{Please insert the reference listed as [REF] on page 8.}

We have inserted the correct reference.

\RC{Please provide more of an introduction to SEM-forests prior to The Present Study section. The manuscript appears to assume much more knowledge about machine learning than many readers have.}

As requested, we now provide a more extensive introduction to SEM-forests prior to The Present Study. This section reads:

`r get_revision( "semforests")`

\RC{Please provide more information about the participants (mean and range of age of adolescents and parents at time of recruitment, race/ethnicity, income, and parental education). This will help contextualize the findings related to demographic characteristics that were predictive of emotion regulation trajectories.}

Comprehensive descriptive statistics about all available demographic characteristics were already reported in Tables 1 and 2.
However, we see that this was not made sufficiently clear.
To address this comment, in the revision, we now state the following:

`r get_revision("demographics", man)`

\RC{How far apart were “waves” of the study?}

We respectfully believe that this may be an oversight on the Reviewer's part, as the original manuscript stated that:

>  From 2006 to 2011, trained interviewers
conducted annual home visits to collect questionnaire data.

To resolve any remaining ambiguity, in the revision, we rephrased this as follows:

`r get_revision( "waves")`

\RC{Did missingeness relate to demographic or emotion regulation variables in the dataset?}

`r get_revision("missingness", letter, quote = F)`

Note, however, that the methods we use are valid regardless of whether missingness is related to other variables in the dataset or not (i.e., valid for MCAR and MAR). 

\RC{Was the statement, “Class solutions with more than two classes were excluded…” an a priori decision, or a statement of what resulted from the attempt to estimate them? Please be clear in the manuscript.}

We thank the Reviewer for pointing out this unfortunate choice of words, which should have been flagged during proof reading.
In fact, entropy is not a criterion for class enumeration, but for evaluating the quality of the chosen solution (see Jung \& Wickrama, 2008). In the Revision, we have attempted to clarify this as follows:

`r get_revision( "entropy")`

\RC{I was curious why the median and plus/minus 1 SD were used for “s” for continuous variables. I would expect the median to be accompanied by percentiles (e.g., 15th and 85th percentiles) or +/- 1 SD to go along with the mean.}

In line with the Reviewer's expectation, we did use the median and 16th and 84th percentile.
The confusion arises from our attempt to explain to the readership what these percentiles mean, by pointing out that these percentiles correspond to +/- 1SD of a standard normal distribution.

We use percentiles is because they do not assume a normal distribution of the predictor, and neither does the model, so this is a good fit.
As we explain in the text, the 16th and 84th percentiles and the median correspond to +/- 1SD and the mean of a standard normal distribution.
We then use the labels "+/- 1SD" in the plots, in an attempt to make the results more understandable, and explain that these correspond to percentiles of a normal distribution in the text.

In the Revision, we have attempted to address this issue by further clarifying that :

`r get_revision( "percentiles")`

\RC{Please correct the finding for sex – it currently reads, “boys girls reported better emotion regulation.”}

Thank you for pointing out this oversight. We have corrected it, along with other typesetting and grammatical mistakes.

\RC{In the first paragraph of the Discussion, where most important predictors are listed, please list parenting behaviors that ranked as highly as aspects currently listed. Throughout the paper, parenting is listed as unimportant, when there are important exceptions that should be more explicit, rather than parenthetical within a negative statement.}

`r get_revision("parents", quote = F)`

To address this comment, we now also mention highly ranked parent-related constructs in the first paragraph of the Discussion:

`r get_revision( "highrankingparent")`

\RC{I do not believe it is accurate to state, “The fact that individual-level predictors were most important suggests that individual assessments might be sufficient.” Just because a factor is not the most important does not mean it is not playing a significant role. Perhaps the most important factors should be prioritized, but it would be contrary to much of developmental theory and many clinical interventions to suggest that it would be best to consider the adolescent as separate from their context. If anything, developmentalists and clinicians are moving towards greater contextualization of individuals and their identities.}

This is a fair point, and the writing here should have been much more nuanced (that was an oversight).
We have rephrased this as follows:

`r get_revision( "riskassessment")`

\RC{It is rightfully noted that this machine learning application was performed within one sample within one nation. There is limited reason to believe it would be universally applicable, especially because it seemed to draw on variables that happened to be available in a dataset, rather than designing the study for this purpose. The paper could provide more information about the cultural values that may impact emotion regulation in this sample to provide readers more information with which to evaluate generalizability to other populations.}

As requested, we now provide more information about cultural values that may impact the generalizability of our findings:

`r get_revision( "culture")`

And also about cultural bias in prior literature:

`r get_revision( "globalnorth")`

\RC{It is not clear how the information on pages 43-65 are to be used. This is not a labeled or formatted table.}

We apologize for the inconvenience. Pages 43-65 are not intended to be used; we were required to attach hard copies of the online supplemental tables in the submission portal, and these were evidently not formatted correctly. They are just spreadsheets, available online, and will not be part of the printed manuscript.

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
